[AMES]
name = "Applied Mechanics & Engin Scis"

[AMES.courses.102]
title = "Mechanical Behavior/Materials"

[AMES.courses.103B]
title = "Mass Transfer"

[AMES.courses.133]
title = "Finite Element Methods"

[AMES.courses.199]
title = "Independent Study/Undergrads"
note = """Students should go to Engineering Building Unit 2, Room 167, to \
  obtain information and department approval for enrollment in AMES 199."""

[ANLD]
name = "Anthropology/Lower Division"

[ANLD.courses.3]
title = "World Prehistory"
catalog = "/courses/ANTH.html#anld3"

[ANRG]
name = "Anthropology/Regional"

[ANRG.courses.126]
title = "Mesoamerica and the Andes"
catalog = "/courses/ANTH.html#anld3"

[BENG]
name = "Bioengineering"

[BENG.courses.199]
title = "Independent Study/Undergrads"
catalog = "/courses/BENG.html#beng199"
note = """Students should go to the Engineering Building Unit I, Room 4103, to \
  obtain information and department approval for enrollment in BENG 199."""

[BGGN]
name = "Biology/Grad/General"

[BGGN.courses.271]
title = "Adv Experimental Methods/Bio"
note = """BGGN 271 is only open to students enrolled in the Integrated \
  Bachelors/Masters Degree Program."""

[BICD]
name = "Biol/Genetics,Cellular&Develop"

[BICD.courses.100]
title = "Genetics"
catalog = "/courses/BIOL.html#bicd100"

[BILD]
name = "Biology/Lower Division"

[BILD.courses.1]
title = "The Cell"
catalog = "/courses/BIOL.html#bild1"

[BILD.courses.10]
title = "Fundamental Concepts/Modrn Bio"
catalog = "/courses/BIOL.html#bild10"

[BILD.courses.24]
title = "Biology of Human Reproduction"
catalog = "/courses/BIOL.html#bild24"

[BILD.courses.82]
title = "Marine Biology"

[BISP]
name = "Biology/Special Studies"

[BISP.courses.199]
title = "Independent Study"
catalog = "/courses/BIOL.html#bisp199"

[CHEM]
name = "Chemistry and Biochemistry"

[CHEM.courses.6A]
title = "General Chemistry"
catalog = "/courses/BIOL.html#bisp199"

[CHEM.courses.140B]
title = "Organic Chemistry"
catalog = "/courses/BIOL.html#bisp199"

[CHEM.courses.140C]
title = "Organic Chemistry"
catalog = "/courses/BIOL.html#bisp199"

[COCU]
name = "Communication and Culture"

[COCU.courses.170]
title = "Advertising and Society"
catalog = "/courses/COGS.html#cogs14"

[COGN]
name = "Communication/General"

[COGN.courses.20]
title = "Introduction to Communication"
catalog = "/courses/COMM.html#cogn20"

[COGN.courses.199]
title = "Independent Study/Communicatn"
catalog = "/courses/COMM.html#cogn199"

[COGS]
name = "Cognitive Science"

[COGS.courses.14]
title = "Design & Analysis of Expermnts"
catalog = "/courses/COGS.html#cogs14"

[COGS.courses.199]
title = "Special Project"
catalog = "/courses/COGS.html#cogs14"

[COSF]
name = "Communication as Social Force"

[COSF.courses.175]
title = "Adv Topics/Comm Social Force"
catalog = "/courses/COMM.html#cosf175"

[CSE]
name = "Computer Science & Engineering"

[CSE.courses.8B]
title = "Intro/Computer Science: Java"
catalog = "/courses/COMM.html#cosf175"

[CSE.courses.197]
title = "Field Study/Computer Sci&Engin"
catalog = "/courses/CSE.html#cse197"

[ECE]
name = "Electrical & Computer Engineer"

[ECE.courses.60B]
title = "Circuits and Systems II"

[ECE.courses.197]
title = "Field Study/Electrical&Computr"
catalog = "/courses/ECE.html#ece197"

[ECE.courses.299]
title = "Research"
catalog = "/courses/ECE.html#ece197"

[ECON]
name = "Economics"

[ECON.courses.1B]
title = "Elements of Economics"
catalog = "/courses/ECE.html#ece197"

[ECON.courses.2A]
title = "Introduction to Economics"

[ECON.courses.100B]
title = "Microeconomics"

[ECON.courses.118B]
title = "Law and Economics"

[ECON.courses.131]
title = "Economics of the Environment"

[ECON.courses.151]
title = "Econ/Public Sector:Expenditure"
catalog = "/courses/ECON.html#econ151"

[ECON.courses.181]
title = "Topics in Finance"
catalog = "/courses/ECON.html#econ151"

[ECON.courses.199]
title = "Independent Study"
catalog = "/courses/ECON.html#econ199"
note = """Students should go to the Economics Department Office, ECON 114, to \
  obtain information and department approval for enrollment in ECON 195 \
  and 199."""

[ETHN]
name = "Ethnic Studies"

[ETHN.courses.199]
title = "Independent Study and Research"
catalog = "/courses/ETHN.html#ethn199"

[FPM]
name = "Family and Preventive Medicine"

[FPM.courses.199]
title = "Independent Study"

[HIEU]
name = "History of Europe"

[HIEU.courses.170]
title = "Special Tops/19th Century Euro"

[HIEU.courses.171]
title = "Special Tops/20th Century Euro"
catalog = "/courses/HIST.html#hieu171"

[HILA]
name = "History of Latin America"

[HILA.courses.118]
title = "US Agression/Latin Am 1898-Prs"
catalog = "/courses/HIST.html#hila118"

[HIUS]
name = "History of the United States"

[HIUS.courses.149]
title = "United States in the 1960's"
catalog = "/courses/HIST.html#hius149"

[HUM]
name = "Humanities"

[HUM.courses.5]
title = "Modern Culture (1848-Present)"
catalog = "/courses/HIST.html#hius149"

[IRGN]
name = "Intrnat Relat/Pac Study-Generl"

[IRGN.courses.499]
title = "Independent Research"
catalog = "/courses/MMW.html#mmw5"

[LTEN]
name = "Literatures in English"

[LTEN.courses.159]
title = "20th Century Amer Lit&Culture"
catalog = "/courses/MMW.html#mmw5"

[LTEN.courses.199]
title = "Special Studies"
catalog = "/courses/LIT.html#lten199"

[LTGN]
name = "Literature/General"

[LTGN.courses.4M]
title = "Fiction&Film/20th Cen/Multiple"
catalog = "/courses/LIT.html#lten199"

[LTGN.courses.172]
title = "Adolescent Literature"

[LTSP]
name = "Literature/Spanish"

[LTSP.courses.50B]
title = "Readings/Latin Amer Literature"
catalog = "/courses/LIT.html#ltsp50b"

[LTSP.courses.119C]
title = "Cervantes: Don Quijote"
catalog = "/courses/LIT.html#ltsp50b"

[LTSP.courses.199]
title = "Special Studies"
catalog = "/courses/LIT.html#ltsp199"

[LTWR]
name = "Literature/Writing"

[LTWR.courses.100]
title = "Short Fiction"
catalog = "/courses/LIT.html#ltwr100"

[MATH]
name = "Mathematics"

[MATH.courses.10B]
title = "Calculus"
catalog = "/courses/MATH.html#math10b"

[MATH.courses.10C]
title = "Calculus"
catalog = "/courses/MATH.html#math10c"

[MATH.courses.20B]
title = "Calculus/Science & Engineering"
catalog = "/courses/MATH.html#math20b"

[MATH.courses.20D]
title = "Differentl Equatns&VectorCalc"
catalog = "/courses/MATH.html#math20b"

[MATH.courses.120A]
title = "Elements of Complex Analysis"
catalog = "/courses/MATH.html#math120a"

[MED]
name = "Medicine"

[MED.courses.199]
title = "Independent Study"

[MMW]
name = "Making of the Modern World"

[MMW.courses.5]
title = "Revolution,Industry & Empire"
catalog = "/courses/MMW.html#mmw5"
note = """Discussion sections for MMW 5 begin on Tuesday, January 5, 1999. \
  Students who place their names on a Registrar wait list through TeSS or \
  WebReg must come to the MMW/Writing Program office in 412 UCtr no later than \
  the end of the first week of classes, January 8, 1999."""

[MUS]
name = "Music"

[MUS.courses.80]
title = "Special Topics in Music"
catalog = "/courses/MUS.html#mus80"

[NEU]
name = "Neurosciences"

[NEU.courses.199]
title = "Clinical Independent Study"
catalog = "/courses/MUS.html#mus80"

[PATH]
name = "Pathology"

[PATH.courses.199]
title = "Independent Study"

[PEDS]
name = "Pediatrics"

[PEDS.courses.199]
title = "Independent Study"

[PHYS]
name = "Physics"

[PHYS.courses.1B]
title = "Heat, Electricity & Magnetism"

[PHYS.courses.1C]
title = "Waves, Radiation,& Modern Phys"

[PHYS.courses.1CL]
title = "Gen Phys Lab-Elec&Magnetsm&Opt"
note = """Please see the note at the beginning of Physics course listings \
  regarding attendance at the first lab section. Week one - Mar 30-Apr 3 all \
  labs meet for organization Week two - Apr 6-10 - all labs meet for \
  experiment one Week three - Apr 13 - week 10 students attend labs every \
  other week for experiments 2-5 schedule will be provided at the first \
  meeting. Students who enroll in PHYS 1CL will be charged a $15.00 lab fee \
  which will be assessed with registration fees."""

[PHYS.courses.199]
title = "Research for Undergraduates"
catalog = "/courses/PHYS.html#phys199"

[POLI]
name = "Political Science"

[POLI.courses.10]
title = "Intro/Poli Sci:Amer Politics"
catalog = "/courses/PHYS.html#phys199"

[POLI.courses.102JJ]
title = "Field Research/Urban Politics"
catalog = "/courses/PHYS.html#phys199"

[POLI.courses.103A]
title = "Calif Government & Politics"

[POLI.courses.199]
title = "Independent Study"
catalog = "/courses/POLI.html#poli199"
note = """Students should go to the Political Science Department Office, \
  Social Science Building, 3rd floor, to obtain information and department \
  approval for enrollment in Political Science 199."""

[PSY]
name = "Psychiatry"

[PSY.courses.199]
title = "Independent Study"

[PSYC]
name = "Psychology"

[PSYC.courses.2]
title = "Gen Psych:Biological Foundatns"
catalog = "/courses/PSYC.html#psyc2"

[PSYC.courses.4]
title = "General Psychology: Behavioral"
catalog = "/courses/PSYC.html#psyc4"

[PSYC.courses.60]
title = "Introduction to Statistics"
catalog = "/courses/PSYC.html#psyc60"

[PSYC.courses.102]
title = "Intro/Sensation & Perception"
catalog = "/courses/PSYC.html#psyc102"

[PSYC.courses.105]
title = "Introduction/Cognitive Psych"
catalog = "/courses/PSYC.html#psyc105"

[PSYC.courses.141]
title = "Evolution and Human Nature"
catalog = "/courses/PSYC.html#psyc141"

[PSYC.courses.144]
title = "Memory and Amnesia"
catalog = "/courses/PSYC.html#psyc144"

[PSYC.courses.168]
title = "Psychological Disorders/Child"
catalog = "/courses/PSYC.html#psyc168"

[PSYC.courses.169]
title = "Brain Damage & Mental Function"
catalog = "/courses/PSYC.html#psyc169"

[PSYC.courses.170]
title = "Intro to Cognitive Neuropsych"
catalog = "/courses/PSYC.html#psyc170"

[PSYC.courses.172]
title = "Psychology of Human Sexuallity"
catalog = "/courses/PSYC.html#psyc170"

[PSYC.courses.176]
title = "Functional Neuroanatomy"
catalog = "/courses/PSYC.html#psyc170"

[PSYC.courses.181]
title = "Drugs And Behavior"
catalog = "/courses/PSYC.html#psyc181"

[PSYC.courses.199]
title = "Independent Study"
catalog = "/courses/PSYC.html#psyc199"
note = """Students should see Hildegard Kleiser in the Psychology Department \
  Office, McGill Hall Annex 1533, to obtain information and department \
  approval for enrollment in Psychology 199."""

[RAD]
name = "Radiology"

[RAD.courses.199]
title = "Independent Study"

[RMED]
name = "Reproductive Medicine"

[RMED.courses.199]
title = "Independent Study"

[SOCA]
name = "Soc/Theory & Methods"

[SOCA.courses.100]
title = "Classical Sociological Theory"

[SOCB]
name = "Soc/Cult, Lang, & Soc Interact"

[SOCB.courses.145]
title = "Violence and Society"
catalog = "/courses/SOC.html#socb145"

[SOCC]
name = "Soc/Soc Organiz & Institutions"

[SOCC.courses.157]
title = "Religion/Contemporary Society"
catalog = "/courses/SOC.html#socc157"

[SOCL]
name = "Soc/Lower Division"

[SOCL.courses.1B]
title = "The Study of Society"
catalog = "/courses/SOC.html#socc157"

[SOSC]
name = "Social Science"

[SOSC.courses.60]
title = "Elem Stats: Social Sciences"
catalog = "/courses/SOC.html#socc157"
note = """SOSC 60 will only be offered Fall 1997 and Spring 1998; it will not \
  be offered Winter 1998."""

[SURG]
name = "Surgery"

[SURG.courses.199]
title = "Independent Study"

[TEP]
name = "Teacher Education Program"

[TEP.courses.199]
title = "Special Studies"
catalog = "/courses/TEP.html#tep199"

[THAC]
name = "Theatre/Acting"

[THAC.courses.107]
title = "Improvisation for the Theatre"
catalog = "/courses/TEP.html#tep199"

[USP]
name = "Urban Studies & Planning"

[USP.courses.2]
title = "Urban World System"
catalog = "/courses/TEP.html#tep199"

[USP.courses.199]
title = "Independent Study"
catalog = "/courses/USP.html#usp199"

[VIS]
name = "Visual Arts"

[VIS.courses.194]
title = "Fantasy In Film"
catalog = "/courses/USP.html#usp199"

[VIS.courses.199]
title = "Special Studies"
catalog = "/courses/VIS.html#vis199"

[WCWP]
name = "Warren College Writing Program"

[WCWP.courses.10B]
title = "The Writing Course"
catalog = "/courses/VIS.html#vis199"
