[ANES]
name = "Anesthesiology"

[ANES.courses.296]
title = "Independent Study"

[ANES.courses.401]
title = "Anesthesiology Clerkship"

[ANES.courses.427]
title = "Surgical Critical Care"

[ANES.courses.496]
title = "Clinical Independent Study"

[CLIN]
name = "Clinical Psychology"

[CLIN.courses.296]
title = "Independent Study"
catalog = "/courses/CLIN.html#clin296"

[FPM]
name = "Family and Preventive Medicine"

[FPM.courses.296]
title = "Community Med Independnt Rsrch"

[FPM.courses.299]
title = "Comm/Fam Med Indepndnt Stu-ISP"

[FPM.courses.426]
title = "Family Medicine Clerkship"

[FPM.courses.429]
title = "Geriatrics Clerkship"

[FPM.courses.430]
title = "Clinical Selective"

[FPM.courses.431]
title = "Sports Medicine"

[FPM.courses.432]
title = "Rural Health Clerkship"

[FPM.courses.433]
title = "Cross-Cultural Clerkship"

[FPM.courses.435]
title = "Preceptorshp Electv-SD Hospice"

[FPM.courses.496]
title = "Clinical Independent Study"

[MED]
name = "Medicine"

[MED.courses.296]
title = "Independent Research"

[MED.courses.299]
title = "Medicine Independnt Study Proj"

[MED.courses.401]
title = "Medicine Core Clerkship"

[MED.courses.425]
title = "Internal Med/Geriatric Consult"

[MED.courses.426]
title = "Coronary Care Unit Clerkship"

[MED.courses.427]
title = "Clinical Mgmt HIV/AIDS Infectn"

[MED.courses.428]
title = "Clinical Dermatology"

[MED.courses.429]
title = "Intensive Course/Clinical Med"

[MED.courses.430]
title = "Clinical Cardiology"

[MED.courses.431]
title = "Clerkship/Infectious Diseases"

[MED.courses.432]
title = "Clin Hematolgy/Oncolgy Clrkshp"

[MED.courses.433]
title = "Clrkshp Clin Endocrinlgy-Metab"

[MED.courses.435]
title = "Pulmonary Inpatient Consul Ser"

[MED.courses.438]
title = "Clin Pulmonary Physiology Lab"

[MED.courses.440]
title = "Clerkship/Rural Internal Med"

[MED.courses.444]
title = "Critical Care Med-VA Hospital"

[MED.courses.452]
title = "Intro/Multidiscplnry Geriatrcs"

[MED.courses.453]
title = "Clerkship/Clinical Nephrology"

[MED.courses.455]
title = "Clerkship in Gastroenterology"

[MED.courses.457]
title = "Rheumatology-Clinical Elective"

[MED.courses.463]
title = "Clrkshp/Crit Care/Internal Med"

[MED.courses.465]
title = "Gen Med-Adv Clrkshp Ambul Care"

[MED.courses.466]
title = "Adv Med/Inpatient Clerkship"

[MED.courses.467]
title = "Fourth Yr Subintrnshp Med-VAMC"

[MED.courses.468]
title = "Gen Med Adv Clerkshp-Inpatient"

[MED.courses.470]
title = "Medcl Consultation/Pre-op Eval"

[MED.courses.496]
title = "Clinical Independent Study"

[NEU]
name = "Neurosciences"

[NEU.courses.296]
title = "Neurosciences Independnt Rsrch"

[NEU.courses.299]
title = "Neurosciences Research"
catalog = "/courses/NEU.html#neu299"

[NEU.courses.401]
title = "Neurology Core Clerkship"

[NEU.courses.426]
title = "Sub-Internship/Pediatric Neuro"

[NEU.courses.427]
title = "Neurology Out-Patient"

[NEU.courses.428]
title = "Spinal Cord Injury Rehab"

[NEU.courses.496]
title = "Clinical Independent Study"

[NURS]
name = "Nurse Practitioner Program"

[NURS.courses.208]
title = "Issues in Primary Care"

[NURS.courses.222D]
title = "Nurse-Midwifery Specialty Sem"

[NURS.courses.496]
title = "Clinical Independent Study"

[OPTH]
name = "Ophthalmology"

[OPTH.courses.296]
title = "Independent Study"

[OPTH.courses.425]
title = "Subinternship in Ophthalmology"

[OPTH.courses.496]
title = "Clinical Independent Study"

[ORTH]
name = "Orthopaedics"

[ORTH.courses.296]
title = "Orthopaedics Independent Rsrch"

[ORTH.courses.425]
title = "Subinternship/Orthopaedics/MC"

[ORTH.courses.426]
title = "Subin/Ambulatory Orthopaedics"

[ORTH.courses.427]
title = "Subinternship/Orthopaedics/VA"

[ORTH.courses.428]
title = "Subin/Reconstrctv Orthopaedics"

[ORTH.courses.429]
title = "Subint/Orthopaedic Spine Surg"

[ORTH.courses.430]
title = "Clrkshp/Hand&Microvasculr Surg"

[ORTH.courses.431]
title = "Clrkshp/Pediatric Orthopaedics"

[ORTH.courses.432]
title = "Clrkshp/Rehabilitatn Medicine"

[ORTH.courses.433]
title = "Clrkshp/Spine&Joint Reconditng"

[ORTH.courses.496]
title = "Clinical Independent Study"

[PATH]
name = "Pathology"

[PATH.courses.296]
title = "Pathology Independent Research"
catalog = "/courses/PATH.html#path296"

[PATH.courses.401A]
title = "Pathology Clerkship/Autopsy"

[PATH.courses.401B]
title = "Pathology Clerkship/Cytology"

[PATH.courses.401C]
title = "Clerkship in Pathology"

[PATH.courses.401S]
title = "Pathology Clerkship/Surgery"

[PATH.courses.401W]
title = "Clerkship/Clinico-Path Correla"

[PATH.courses.425]
title = "Pathology Clerkship/Forensic"

[PATH.courses.426]
title = "Pathology Clerkship/Pediatric"

[PATH.courses.496]
title = "Clinical Independent Study"

[PEDS]
name = "Pediatrics"

[PEDS.courses.296]
title = "Pediatrics Independent Resrch"

[PEDS.courses.299]
title = "Pediatric Indepndnt Study Proj"

[PEDS.courses.401]
title = "Pediatric Core Clerkship"

[PEDS.courses.426]
title = "Clin Clerkshp/Pediatric Cardio"

[PEDS.courses.427]
title = "Sub-Internship/Inpatient Peds"

[PEDS.courses.428]
title = "Subintrnshp/Neonatal/Perinatal"

[PEDS.courses.429]
title = "Subintrnshp/Pediatrc Emerg Med"

[PEDS.courses.430]
title = "Pediatric Infectious Diseases"

[PEDS.courses.431]
title = "Subinternship/Ambulatory Peds"

[PEDS.courses.432]
title = "Clin Experience/Adolescent Med"

[PEDS.courses.433]
title = "Elect/Clin Ped Hematolgy/Oncol"

[PEDS.courses.434]
title = "Clerkship/Pediatric Nephrology"

[PEDS.courses.436]
title = "Pediatric Intensive Care"

[PEDS.courses.496]
title = "Clinical Independent Study"

[PSY]
name = "Psychiatry"

[PSY.courses.296]
title = "Independnt Readngs/Stdy in Psy"

[PSY.courses.299]
title = "Psychiatry Independnt Stdy Pro"

[PSY.courses.401]
title = "Psychiatry Core Clerkship"

[PSY.courses.403]
title = "Adv Clin Psy Outpatient Electv"

[PSY.courses.425]
title = "Consultatn/Liaison Psy Clrkshp"

[PSY.courses.426]
title = "Geriatric Psychiatry"

[PSY.courses.427]
title = "Psychiatric Crisis Evaluation"

[PSY.courses.428]
title = "Primary Care of Alcoholism"

[PSY.courses.429]
title = "Child Psychiatry"

[PSY.courses.496]
title = "Clinical Independent Study"

[RAD]
name = "Radiology"

[RAD.courses.296]
title = "Radiology Independent Research"

[RAD.courses.299]
title = "Radiology Independent Study"

[RAD.courses.401]
title = "General Radiology"

[RAD.courses.426]
title = "Clin Correlatn/Diagnostic Rad"

[RAD.courses.427]
title = "Vascular Radiology"

[RAD.courses.428]
title = "Body Computed Tomography"

[RAD.courses.429]
title = "Radiation Therapy Clerkship"

[RAD.courses.430]
title = "Musculoskeletal Radiology"

[RAD.courses.431]
title = "Introduction/Ultrasonography"

[RAD.courses.432]
title = "Imaging and Interventinal Rad"

[RAD.courses.434]
title = "Chest Radiology"

[RAD.courses.496]
title = "Clinical Independent Study"

[RMED]
name = "Reproductive Medicine"

[RMED.courses.296]
title = "Repro Endocrinolgy Indepen Res"

[RMED.courses.299]
title = "Repro Med Indepen Study Projct"

[RMED.courses.401]
title = "Obstetrcs&Gyneclgy Cor Clrkshp"

[RMED.courses.426]
title = "Gen Obstetrics & Gynecology"

[RMED.courses.427]
title = "Adv Clerkship/Reproductive Med"

[RMED.courses.428]
title = "Subinternship in Perinatology"

[RMED.courses.430]
title = "Adv Clerkshp/Gynecologic Oncol"

[RMED.courses.431]
title = "Adv Preceptorshp/Perinatal Med"

[RMED.courses.432]
title = "Subintrnshp/Obstetrics&Gynecol"

[RMED.courses.433]
title = "UCSD-Mercy Ob-Gyn Subinternshp"

[RMED.courses.496]
title = "Clinical Independent Study"

[SOMC]
name = "School of Medicine Core Crses"

[SOMC.courses.401]
title = "Primary Care Core Clerkship"

[SOMC.courses.401B]
title = "Prim Care Core Clkship:Fam Med"

[SOMC.courses.420]
title = "Subinternship/Emergency Med"

[SOMI]
name = "Sch of Med Interdisciplinary"

[SOMI.courses.222]
title = "Advanced Cardiac Life Support"

[SOMI.courses.224]
title = "Pediatric Advancd Life Support"

[SOMI.courses.421]
title = "Multdiscp Clin Clerkshp/Mexico"

[SURG]
name = "Surgery"

[SURG.courses.296]
title = "Surgery Independent Research"

[SURG.courses.299]
title = "Surgery Independent Study Proj"

[SURG.courses.401]
title = "Surgery Core Clerkship"

[SURG.courses.425]
title = "Subinternship Trauma Unit - UH"

[SURG.courses.427]
title = "Surgical Critical Care"

[SURG.courses.428]
title = "In Depth Elec/Surgical Oncolgy"

[SURG.courses.429]
title = "Subinternship in General Surg"

[SURG.courses.431]
title = "Clerkship/Transplntn (Abdomnl)"

[SURG.courses.433]
title = "Subint/Otol-Head&Neck Surg UH"

[SURG.courses.434]
title = "Subint/Otol-Head&Neck Surg VA"

[SURG.courses.435]
title = "Preceptorship in Otology"

[SURG.courses.437]
title = "Subin/Cardiothoracic Surg UH"

[SURG.courses.438]
title = "Subin/Cardiothoracic Surg VA"

[SURG.courses.443]
title = "Subinternship in Urology"

[SURG.courses.445]
title = "Subinternship/Plastic Surgery"

[SURG.courses.448]
title = "Subinternshp/Pediatric Surgery"

[SURG.courses.454]
title = "Subinternship/Neurosurgery UH"

[SURG.courses.455]
title = "Clin Clrkshp/Pediatric Urology"

[SURG.courses.466]
title = "Subinternship in Burn Surgery"

[SURG.courses.467]
title = "Private Generl Surg Experience"

[SURG.courses.496]
title = "Clinical Independent Study"
