[ANGN]
name = "Anthropology/General"

[ANGN.courses.120]
title = "Anthropology of Religion"
catalog = "/courses/ANTH.html#angn120"

[ANGN.courses.172]
title = "Life-History"
catalog = "/courses/ANTH.html#angn172"

[ANLD]
name = "Anthropology/Lower Division"

[ANLD.courses.2]
title = "Human Origins"
catalog = "/courses/ANTH.html#anld2"

[BENG]
name = "Bioengineering"

[BENG.courses.1]
title = "Introduction to Bioengineering"
catalog = "/courses/BENG.html#beng1"

[BGGN]
name = "Biology/Grad/General"

[BGGN.courses.271]
title = "Adv Experimental Methods/Bio"
catalog = "/courses/BIOL.html#bggn271"
note = """BGGN 271 is only open to students enrolled in the Integrated \
  Bachelors/Masters Degree Program."""

[BIBC]
name = "Biology/Biochemistry"

[BIBC.courses.102]
title = "Metabolic Biochemistry"
catalog = "/courses/BIOL.html#bibc102"

[BIBC.courses.120]
title = "Nutrition"
catalog = "/courses/BIOL.html#bibc120"

[BICD]
name = "Biol/Genetics,Cellular&Develop"

[BICD.courses.100]
title = "Genetics"
catalog = "/courses/BIOL.html#bicd100"

[BICD.courses.136]
title = "AIDS Science and Society"
catalog = "/courses/BIOL.html#bicd136"

[BILD]
name = "Biology/Lower Division"

[BILD.courses.1]
title = "The Cell"
catalog = "/courses/BIOL.html#bild1"

[BILD.courses.2]
title = "Multicellular Life"
catalog = "/courses/BIOL.html#bild2"

[BILD.courses.10]
title = "Fundamental Concepts/Modrn Bio"
catalog = "/courses/BIOL.html#bild10"

[BILD.courses.12]
title = "Neurobiology and Behavior"
catalog = "/courses/BIOL.html#bild12"

[BILD.courses.24]
title = "Biology of Human Reproduction"
catalog = "/courses/BIOL.html#bild24"

[BILD.courses.82]
title = "Marine Biology"

[BIMM]
name = "Biology/Molec Biol, Microbiol"

[BIMM.courses.100]
title = "Molecular Biology"
catalog = "/courses/BIOL.html#bimm100"

[BISP]
name = "Biology/Special Studies"

[BISP.courses.196]
title = "Honors Thesis in Biology"
catalog = "/courses/BIOL.html#bisp196"

[BISP.courses.199]
title = "Independent Study"
catalog = "/courses/BIOL.html#bisp199"

[CGS]
name = "Critical Gender Studies"

[CGS.courses.102]
title = "Topics in Critical Gender Stds"
catalog = "/courses/CGS.html#cgs102"

[CHEM]
name = "Chemistry and Biochemistry"

[CHEM.courses.140B]
title = "Organic Chemistry"
catalog = "/courses/CGS.html#cgs102"

[CHIN]
name = "Chinese Studies"

[CHIN.courses.150]
title = "Intens Sum Language&Cult Prog"

[COCU]
name = "Communication and Culture"

[COCU.courses.100]
title = "Intro/Communication & Culture"
catalog = "/courses/COMM.html#cocu100"

[COCU.courses.175]
title = "Adv Topics/Communication Cult"
catalog = "/courses/COMM.html#cocu175"

[COGN]
name = "Communication/General"

[COGN.courses.20]
title = "Introduction to Communication"
catalog = "/courses/COMM.html#cogn20"

[COGN.courses.150]
title = "Senior Seminar/Communication"
catalog = "/courses/COMM.html#cogn150"

[COGN.courses.198]
title = "Directed Group Study/Comm"
catalog = "/courses/COMM.html#cogn198"

[COGN.courses.199]
title = "Independent Study/Communicatn"
catalog = "/courses/COMM.html#cogn199"

[COGR]
name = "Communication/Graduate"

[COGR.courses.261]
title = "Mediational Approach-Cult/Mind"
catalog = "/courses/COMM.html#cogr261"

[COGS]
name = "Cognitive Science"

[COGS.courses.17]
title = "Neurobiology of Cognition"
catalog = "/courses/COGS.html#cogs17"

[COGS.courses.160]
title = "Seminar on Special Topics"
catalog = "/courses/COGS.html#cogs160"

[COGS.courses.199]
title = "Special Project"
catalog = "/courses/COGS.html#cogs199"

[COHI]
name = "Communication/Human Info Proc"

[COHI.courses.175]
title = "Advanced Topics/Communication"
catalog = "/courses/COMM.html#cohi175"

[CONT]
name = "Contemporary Issues"

[CONT.courses.1]
title = "The University in Society"
catalog = "/courses/CONT.html#cont1"

[COSF]
name = "Communication as Social Force"

[COSF.courses.100]
title = "Intro/Communication/Soc Force"
catalog = "/courses/COMM.html#cosf100"

[COSF.courses.140B]
title = "Comparatv Media Systems:Europe"
catalog = "/courses/COMM.html#cosf140b"

[COSF.courses.175]
title = "Adv Topics/Comm Social Force"
catalog = "/courses/COMM.html#cosf175"

[CSE]
name = "Computer Science & Engineering"

[CSE.courses.20]
title = "Intro/Discrete Mathematics"
catalog = "/courses/CSE.html#cse20"
note = "CSE 20 is equivalent to MATH 15A."

[CSE.courses.21]
title = "Math/Algorithm&Systems Analys"
catalog = "/courses/CSE.html#cse21"
note = "CSE 21 is equivalent to MATH 15B."

[CSE.courses.142]
title = "Advanced Digital Logic Design"
catalog = "/courses/CSE.html#cse142"

[CSE.courses.197]
title = "Field Study/Computer Sci&Engin"
catalog = "/courses/CSE.html#cse197"
note = """Students should go to APM 3402 or call (858)534-3621 \
  or (858)822-1535 to obtain information and department approval for \
  enrollment in CSE 197, 198, and 199."""

[ECE]
name = "Electrical & Computer Engineer"

[ECE.courses.53B]
title = "Fundamentl/Electricl Enginr II"
catalog = "/courses/ECE.html#ece53b"
note = """Attendance at the first lab of ECE 53B is MANDATORY for all \
  students. Students who do not attend the first lab should have someone \
  represent him/her during the lab. Those who fail to attend or are without \
  representation may lose their registration right to continue in the class. \
  Responsibility, however, for dropping the course from the Registrar's \
  records belongs to the student."""

[ECE.courses.60B]
title = "Circuits and Systems II"

[ECE.courses.60L]
title = "Circuits & Systems Laboratory"

[ECE.courses.103]
title = "Fundamntls/Devices & Materials"
catalog = "/courses/ECE.html#ece103"

[ECE.courses.107]
title = "Electromagnetism"
catalog = "/courses/ECE.html#ece107"

[ECE.courses.161A]
title = "Intr/Digital Signal Processing"
catalog = "/courses/ECE.html#ece161a"

[ECON]
name = "Economics"

[ECON.courses.1A]
title = "Elements of Economics"
catalog = "/courses/ECE.html#ece161a"

[ECON.courses.1B]
title = "Elements of Economics"
catalog = "/courses/ECE.html#ece161a"

[ECON.courses.100B]
title = "Microeconomics"
catalog = "/courses/ECE.html#ece161a"

[ECON.courses.110A]
title = "Macroeconomics"

[ECON.courses.120B]
title = "Econometrics"

[ECON.courses.178]
title = "Economic&Business Forecasting"

[ECON.courses.179]
title = "Decisions in the Public Sector"
catalog = "/courses/ECON.html#econ179"

[HIAF]
name = "History of Africa"

[HIAF.courses.111]
title = "Modern Africa Since 1880"
catalog = "/courses/HIST.html#hiaf111"

[HIEA]
name = "History of East Asia"

[HIEA.courses.162]
title = "History of Women in China"
catalog = "/courses/HIST.html#hiea162"

[HIGR]
name = "History, Graduate"

[HIGR.courses.298]
title = "Directed Reading"
catalog = "/courses/HIST.html#higr298"

[HILA]
name = "History of Latin America"

[HILA.courses.105]
title = "Medicne, Ethn & State/Lat Amer"

[HILA.courses.118]
title = "US Agression/Latin Am 1898-Prs"
catalog = "/courses/HIST.html#hila118"

[HILD]
name = "History, Lower Division"

[HILD.courses.2C]
title = "United States History"
catalog = "/courses/HIST.html#hild2c"

[HINE]
name = "History of the Near East"

[HINE.courses.109]
title = "Lrning to Read Biblical Hebrew"
catalog = "/courses/HIST.html#hild2c"

[HINE.courses.109B]
title = "Lrng to Read Biblical HebrewII"
catalog = "/courses/HIST.html#hine109b"

[HITO]
name = "History Topics"

[HITO.courses.102]
title = "East Asian Religious Tradition"
catalog = "/courses/HIST.html#hito102"

[HITO.courses.127]
title = "Seafaring in American History"

[HIUS]
name = "History of the United States"

[HIUS.courses.155B]
title = "Religion&Law:Cvl War to Presnt"
catalog = "/courses/HIST.html#hius155b"

[HUM]
name = "Humanities"

[HUM.courses.4]
title = "Enlightmnt,Romnt,Rev/1660-1848"
catalog = "/courses/HUM.html#hum4"

[LIGN]
name = "Linguistics/General"

[LIGN.courses.3]
title = "Language/Social & Cult Phenomn"
catalog = "/courses/LING.html#lign3"

[LTCS]
name = "Literature/Cultural Studies"

[LTCS.courses.110]
title = "Popular Culture"
catalog = "/courses/LIT.html#ltcs110"

[LTEN]
name = "Literatures in English"

[LTEN.courses.114]
title = "Shakespeare III:Stage,Film,&TV"
catalog = "/courses/LIT.html#lten114"

[LTFR]
name = "Literature/French"

[LTFR.courses.2A]
title = "Intermediate French I"
catalog = "/courses/LIT.html#ltfr2a"

[LTFR.courses.115]
title = "Themes/Intellect&Literary Hist"
catalog = "/courses/LIT.html#ltfr2a"

[LTSP]
name = "Literature/Spanish"

[LTSP.courses.50C]
title = "Readings/Latin American Topics"
catalog = "/courses/LIT.html#ltsp50c"

[LTWL]
name = "Literatures of the World"

[LTWL.courses.4M]
title = "Fiction&Film/20th Cen/Multiple"
catalog = "/courses/LIT.html#ltwl4m"

[LTWR]
name = "Literature/Writing"

[LTWR.courses.8B]
title = "Craft of Writing: Poetry"
catalog = "/courses/LIT.html#ltwl4m"
note = """LTWR 8B, LA A50, represents readings in the New Writing Series. \
  Students are required to attend 3 readings during the quarter. See \
  Literature Department for details."""

[LTWR.courses.100]
title = "Short Fiction"
catalog = "/courses/LIT.html#ltwr100"
note = """Courses numbered 100-128 are writing workshops. Six of these are \
  required for the Literature/Writing major."""

[LTWR.courses.115]
title = "Experimental Writing"
catalog = "/courses/LIT.html#ltwr115"

[LTWR.courses.120]
title = "Personal Narrative"
catalog = "/courses/LIT.html#ltwr120"

[MAE]
name = "Mechanical & Aerospace Engin"

[MAE.courses.5]
title = "Quantitative Computer Skills"
catalog = "/courses/MAE.html#mae5"

[MAE.courses.9]
title = "C/C++ Programming"
catalog = "/courses/MAE.html#mae9"

[MAE.courses.20]
title = "Elements of Materials Science"
catalog = "/courses/MAE.html#mae20"

[MAE.courses.101B]
title = "Advanced Fluid Mechanics"
catalog = "/courses/MAE.html#mae101b"

[MAE.courses.105]
title = "Intro To Mathematical Physics"
catalog = "/courses/MAE.html#mae105"

[MAE.courses.107]
title = "Computational Methods/Engineer"
catalog = "/courses/MAE.html#mae107"

[MAE.courses.110A]
title = "Thermodynamics"
catalog = "/courses/MAE.html#mae110a"

[MAE.courses.130B]
title = "Mechanics II: Dynamics"
catalog = "/courses/MAE.html#mae130b"

[MAE.courses.131A]
title = "Fundamentals/Solid Mechanics I"
catalog = "/courses/MAE.html#mae131a"

[MAE.courses.143A]
title = "Signals and Systems"
catalog = "/courses/MAE.html#mae143a"

[MAE.courses.143B]
title = "Linear Control"
catalog = "/courses/MAE.html#mae143b"

[MATH]
name = "Mathematics"

[MATH.courses.10B]
title = "Calculus"
catalog = "/courses/MATH.html#math10b"

[MATH.courses.10C]
title = "Calculus"
catalog = "/courses/MATH.html#math10c"

[MATH.courses.20B]
title = "Calculus/Science & Engineering"
catalog = "/courses/MATH.html#math20b"

[MATH.courses.21D]
title = "Intro/Differential Equations"

[MATH.courses.109]
title = "Mathematical Reasoning"
catalog = "/courses/MATH.html#math109"

[MATH.courses.120A]
title = "Elements of Complex Analysis"
catalog = "/courses/MATH.html#math120a"

[MATH.courses.310]
title = "Algebraic Think/Algebra 1 Tchr"

[MMW]
name = "Making of the Modern World"

[MMW.courses.5]
title = "Revolution,Industry & Empire"
catalog = "/courses/MMW.html#mmw5"

[MMW.courses.6]
title = "Twentieth Century and Beyond"
catalog = "/courses/MMW.html#mmw6"

[MUS]
name = "Music"

[MUS.courses.80]
title = "Special Topics in Music"
catalog = "/courses/MUS.html#mus80"

[MUS.courses.111]
title = "Topics/World Music Traditions"
catalog = "/courses/MUS.html#mus111"

[PHIL]
name = "Philosophy"

[PHIL.courses.10]
title = "Introduction to Logic"
catalog = "/courses/PHIL.html#phil10"

[PHYS]
name = "Physics"

[PHYS.courses.1A]
title = "Mechanics"
catalog = "/courses/PHIL.html#phil10"
note = "Labs begin on Monday, September 30."

[PHYS.courses.1B]
title = "Electric, Magnetism&Thermodyn"
catalog = "/courses/PHIL.html#phil10"

[PHYS.courses.1C]
title = "Diffusion, Radiation&Mod Phys"
catalog = "/courses/PHIL.html#phil10"

[PHYS.courses.2B]
title = "Phys-Electricity and Magnetism"
catalog = "/courses/PHYS.html#phys2b"

[PHYS.courses.2C]
title = "Physics-Flu,Wav,Thrmdyn,Optics"
catalog = "/courses/PHYS.html#phys2c"

[PHYS.courses.2CL]
title = "Phys Lab-Elec,Magnetsm,Wav,Opt"
catalog = "/courses/PHYS.html#phys2cl"

[PHYS.courses.2D]
title = "Phys-Relativity&Quantm Physics"
catalog = "/courses/PHYS.html#phys2d"

[PHYS.courses.5]
title = "The Universe"
catalog = "/courses/PHYS.html#phys5"

[PHYS.courses.11A]
title = "Survey of Physics"

[POLI]
name = "Political Science"

[POLI.courses.11]
title = "Intro/Poli Sci:Compar Politics"
catalog = "/courses/POLI.html#poli11"

[POLI.courses.30]
title = "Political Inquiry"
catalog = "/courses/POLI.html#poli30"

[POLI.courses.110B]
title = "Sovereigns,Subj & Modern State"
catalog = "/courses/POLI.html#poli110b"

[POLI.courses.110C]
title = "Politcl Thought/Kant-Nietzsche"
catalog = "/courses/POLI.html#poli110c"

[POLI.courses.110N]
title = "Theories of Nationalism"
catalog = "/courses/POLI.html#poli110n"

[POLI.courses.112C]
title = "Political Thry&Artistic Vision"

[POLI.courses.121B]
title = "Politics in Israel"
catalog = "/courses/POLI.html#poli121b"

[POLI.courses.122B]
title = "Political Trial/Pol of Justice"
catalog = "/courses/POLI.html#poli122b"

[POLI.courses.142L]
title = "Insurgency and Terrorism"
catalog = "/courses/POLI.html#poli142l"

[PSY]
name = "Psychiatry"

[PSY.courses.199]
title = "Independent Study"

[PSYC]
name = "Psychology"

[PSYC.courses.2]
title = "Gen Psych:Biological Foundatns"
catalog = "/courses/PSYC.html#psyc2"

[PSYC.courses.3]
title = "Gen Psych:Cognitive Foundatns"
catalog = "/courses/PSYC.html#psyc3"

[PSYC.courses.6]
title = "General Psychology: Social"
catalog = "/courses/PSYC.html#psyc6"

[PSYC.courses.60]
title = "Introduction to Statistics"
catalog = "/courses/PSYC.html#psyc60"

[PSYC.courses.101]
title = "Intro/Developmental Psychology"
catalog = "/courses/PSYC.html#psyc101"

[PSYC.courses.103]
title = "Intro/Principles of Behavior"
catalog = "/courses/PSYC.html#psyc103"

[PSYC.courses.105]
title = "Introduction/Cognitive Psych"
catalog = "/courses/PSYC.html#psyc105"

[PSYC.courses.172]
title = "Psychology of Human Sexuality"
catalog = "/courses/PSYC.html#psyc105"

[PSYC.courses.177]
title = "Cog Neuropsychology/Language"

[PSYC.courses.181]
title = "Drugs And Behavior"
catalog = "/courses/PSYC.html#psyc181"

[PSYC.courses.199]
title = "Independent Study"
catalog = "/courses/PSYC.html#psyc199"
note = """Students should see Hildegard Kleiser in the Psychology Department \
  Office, McGill Hall Annex 1533, to obtain information and department \
  approval for enrollment in Psychology 199."""

[RAD]
name = "Radiology"

[RAD.courses.199]
title = "Independent Study"

[SOCA]
name = "Soc/Theory & Methods"

[SOCA.courses.109]
title = "Analysis of Sociological Data"
catalog = "/courses/SOC.html#soca109"

[SOCB]
name = "Soc/Cult, Lang, & Soc Interact"

[SOCB.courses.145]
title = "Violence and Society"
catalog = "/courses/SOC.html#socb145"

[SOCB.courses.162]
title = "Popular Culture"
catalog = "/courses/SOC.html#socb162"

[SOCC]
name = "Soc/Soc Organiz & Institutions"

[SOCC.courses.135]
title = "Medical Sociology"
catalog = "/courses/SOC.html#socc135"

[SOCC.courses.157]
title = "Religion/Contemporary Society"
catalog = "/courses/SOC.html#socc157"

[SOCL]
name = "Soc/Lower Division"

[SOCL.courses.1B]
title = "The Study of Society"
catalog = "/courses/SOC.html#socl1b"

[SOCL.courses.60]
title = "Practice of Social Research"
catalog = "/courses/SOC.html#socl60"

[TEP]
name = "Teacher Education Program"

[TEP.courses.20]
title = "Intro/Principles of Learning"

[THAC]
name = "Theatre/Acting"

[THAC.courses.108]
title = "Advanced Topics"

[THAC.courses.111]
title = "Freeing The Voice"

[THDA]
name = "Theatre/Dance"

[THDA.courses.25]
title = "Music for Dancers"

[THDA.courses.102B]
title = "Ballet III - Advanced I"
note = """THDA 102B has a course material fee of $50.00. Fee will be assessed \
  with registration fees."""

[THDA.courses.141]
title = "Principles of Choreography"

[THDR]
name = "Theatre/Directing & Stage Mgmt"

[THDR.courses.108]
title = "Text Analysis/Actors&Directors"

[THGE]
name = "Theatre/General"

[THGE.courses.10]
title = "Theatre And Film"
note = """Students will be required to view videos outside class meeting \
  times."""

[THGE.courses.124]
title = "Cult Films: Wierdly Dramatic"

[THPW]
name = "Theatre/Playwriting"

[THPW.courses.101]
title = "Playwriting Workshop"

[THPW.courses.104]
title = "Screenwriting"

[USP]
name = "Urban Studies & Planning"

[USP.courses.139]
title = "Race, Gender & Urban Planning"

[USP.courses.179]
title = "Urban Design,Theory & Practice"

[VIS]
name = "Visual Arts"

[VIS.courses.21]
title = "Introduction/Non-Western Art"
catalog = "/courses/VIS.html#vis21"
note = "VIS 21 sections will not meet before the first main lecture."

[VIS.courses.152]
title = "Film in Social Context"
catalog = "/courses/VIS.html#vis152"

[WCWP]
name = "Warren College Writing Program"

[WCWP.courses.10B]
title = "The Writing Course"
catalog = "/courses/VIS.html#vis152"
