[AIP]
name = "Academic Internship Program"

[AIP.courses.197]
title = "Academic Internship Program"
catalog = "/courses/AIP.html#aip197"

[AIP.courses.197F]
title = "Int'l Internship Program"

[AIP.courses.197P]
title = "Public Service Minor Internshp"

[AIP.courses.197PR]
title = "PRIME Program"

[ANAR]
name = "Anthropological Archeology"

[ANAR.courses.100]
title = "Spec Topics/Anth Archaeology"
catalog = "/courses/ANTH.html#anar100"

[ANAR.courses.119S]
title = "Archaeological Field & Lab Cls"

[ANAR.courses.155S]
title = "Stdy Abrd: Ancient Mesoamerica"

[ANAR.courses.157S]
title = "Early Empires of the Andes"
catalog = "/courses/ANTH.html#anar157s"

[ANSC]
name = "Anthropology/Sociocultural"

[ANSC.courses.117GS]
title = "Language and (Multi)Culture"
catalog = "/courses/ANTH.html#ansc117gs"

[ANSC.courses.119GS]
title = "Gesture, Communication & Body"
catalog = "/courses/ANTH.html#ansc119gs"

[ANTH]
name = "Anthropology"

[ANTH.courses.198]
title = "Directed Group Study"
catalog = "/courses/ANTH.html#anth198"

[ANTH.courses.199]
title = "Independent Study"
catalog = "/courses/ANTH.html#anth199"

[BENG]
name = "Bioengineering"

[BENG.courses.196]
title = "Bioeng Industrial Internship"
catalog = "/courses/BENG.html#beng196"

[BENG.courses.199]
title = "Independent Study/Undergrads"
catalog = "/courses/BENG.html#beng199"
note = """Students should go to the Powell-Focht Bioengineering Hall, \
  Room 141, to obtain information and department approval for enrollment in \
  BENG 199."""

[BILD]
name = "Biology/Lower Division"

[BILD.courses.18GS]
title = "Human Impact on the Environmnt"
catalog = "/courses/BIOL.html#bild18gs"

[BIMM]
name = "Biology/Molec Biol, Microbiol"

[BIMM.courses.120GS]
title = "Bacteriology"
catalog = "/courses/BIOL.html#bimm120gs"

[BISP]
name = "Biology/Special Studies"

[BISP.courses.199]
title = "Individual Research for Ugrads"
catalog = "/courses/BIOL.html#bisp199"

[CAT]
name = "Culture, Art, & Technology"

[CAT.courses.125]
title = "Sixth Practicum Writing"
catalog = "/courses/CAT.html#cat125"
note = """-Students must have completed and passed their practicum project or \
  course. -Attendance at lecture and sections is required for CAT 125."""

[CENG]
name = "Chemical Engineering"

[CENG.courses.199]
title = "Independent Study/Undergrads"
catalog = "/courses/CENG.html#ceng199"
note = """Students should go to Engineering Building Unit 2, Room 180, to \
  obtain information and department approval for enrollment in CENG 199."""

[CHEM]
name = "Chemistry and Biochemistry"

[CHEM.courses.99]
title = "Independent Study"
catalog = "/courses/CHEM.html#chem99"

[CHEM.courses.199]
title = "Reading and Research"
catalog = "/courses/CHEM.html#chem199"
note = """Students should come to 4010 York Hall for information and forms to \
  apply for Chemistry 199, Reading and Research."""

[CHIN]
name = "Chinese Studies"

[CHIN.courses.11]
title = "First Year Chinese I"
catalog = "/courses/CHIN.html#chin11"

[CHIN.courses.12]
title = "First Year Chinese II"
catalog = "/courses/CHIN.html#chin12"

[CHIN.courses.13]
title = "First Year Chinese III"
catalog = "/courses/CHIN.html#chin13"

[CHIN.courses.21]
title = "Second Year Chinese"
catalog = "/courses/CHIN.html#chin21"

[CHIN.courses.22]
title = "Second Year Chinese"
catalog = "/courses/CHIN.html#chin22"

[CHIN.courses.23]
title = "Second Year Chinese"
catalog = "/courses/CHIN.html#chin23"

[CHIN.courses.196]
title = "Directed Thesis Research"
catalog = "/courses/CHIN.html#chin196"

[CHIN.courses.199]
title = "Independent Study"
catalog = "/courses/CHIN.html#chin199"

[CLRE]
name = "Clinical Research"

[CLRE.courses.252]
title = "Health Services Research"
catalog = "/courses/CLRE.html#clre252"

[CLRE.courses.256]
title = "Patient-Oriented Research II"
catalog = "/courses/CLRE.html#clre256"

[CLRE.courses.260]
title = "Directed Studies in Clin Rsrch"
catalog = "/courses/CLRE.html#clre260"

[CLRE.courses.261]
title = "Applied Quantitative Analysis"
catalog = "/courses/CLRE.html#clre261"

[CLRE.courses.296]
title = "Independent Study Project"
catalog = "/courses/CLRE.html#clre296"

[COGN]
name = "Communication/General"

[COGN.courses.199]
title = "Independent Study/Communicatn"
catalog = "/courses/COMM.html#cogn199"

[COGS]
name = "Cognitive Science"

[COGS.courses.199]
title = "Special Project"
catalog = "/courses/COGS.html#cogs199"

[CSE]
name = "Computer Science & Engineering"

[CSE.courses.4GS]
title = "Mathematical Beauty in Rome"
catalog = "/courses/CSE.html#cse4gs"

[CSE.courses.6GS]
title = "Mathematical Beauty - Rome Lab"
catalog = "/courses/CSE.html#cse6gs"

[CSE.courses.12]
title = "Basic Data Struct & OO Design"
catalog = "/courses/CSE.html#cse12"
note = "Mandatory attendance is required for CSE 12 discussion sections."

[CSE.courses.197]
title = "Field Study/Computer Sci&Engin"
catalog = "/courses/CSE.html#cse197"
note = """For information on how to enroll in a CSE Special Studies (CSE 197, \
  CSE 198 or CSE 199) contact Pat Raczka at raczka@cs.ucsd.edu or \
  call (858) 534-3621. The Special Studies form is found at http://tinyurl.com/\
  prvyz. To submit the form for department approval, students should go to \
  Engineering Building Unit #3B (EBU3B) room 1231."""

[CSE.courses.198]
title = "Direct Group Study"
catalog = "/courses/CSE.html#cse198"

[CSE.courses.199]
title = "Independent Study"
catalog = "/courses/CSE.html#cse199"

[CSE.courses.298]
title = "Independent Study"
catalog = "/courses/CSE.html#cse298"

[CSE.courses.299]
title = "Research"
catalog = "/courses/CSE.html#cse299"

[DOC]
name = "Dimensions of Culture"

[DOC.courses.3]
title = "Imagination"
catalog = "/courses/DOC.html#doc3"

[ECE]
name = "Electrical & Computer Engineer"

[ECE.courses.190]
title = "Engineering Design"
catalog = "/courses/ECE.html#ece190"
note = """Students should go to the ECE Undergraduate office, Engineering \
  Building Unit 1, Room 2705 or 2707, to obtain a Design enrollment form and \
  department approval for enrollment in ECE 192."""

[ECE.courses.197]
title = "Field Study/Electrical&Computr"
catalog = "/courses/ECE.html#ece197"

[ECE.courses.298]
title = "Independent Study"
catalog = "/courses/ECE.html#ece298"

[ECE.courses.299]
title = "Research"
catalog = "/courses/ECE.html#ece299"

[ECON]
name = "Economics"

[ECON.courses.199]
title = "Independent Study"
catalog = "/courses/ECON.html#econ199"
note = """Students should see the Economics Undergraduate Advisor to obtain \
  information and department approval for enrollment in ECON 195 and \
  ECON 199."""

[EDS]
name = "Education Studies"

[EDS.courses.115]
title = "Cog Development & Education"
catalog = "/courses/EDS.html#eds115"

[EDS.courses.117]
title = "Language, Culture & Education"
catalog = "/courses/EDS.html#eds117"

[EDS.courses.125]
title = "Hist,Polic&Theory/Bilingual Ed"
catalog = "/courses/EDS.html#eds125"

[EDS.courses.128A]
title = "Intro/Teaching&Learning (Elem)"
catalog = "/courses/EDS.html#eds128a"
note = """EDS 130 or 134 is a prerequisite to EDS 128A. This course is open \
  only to seniors and EDS graduate students who intend to apply to our \
  multiple subject credential program. Students enrolling in EDS 134 must come \
  to our offices located on the 3rd floor of Pepper Canyon Hall and complete \
  an informational form. Students should be available a minimum of four to six \
  hours per week for fieldwork. Concurrent enrollment in EDS 139, A00 is \
  required."""

[EDS.courses.128B]
title = "Intro/Teaching&Learning (Elem)"
catalog = "/courses/EDS.html#eds128b"

[EDS.courses.139]
title = "Practicum in Teaching/Learning"
catalog = "/courses/EDS.html#eds139"
note = "EDS 139 is a required co-requisite for EDS 129A, 130, 134, 136."

[EDS.courses.199]
title = "Special Studies"
catalog = "/courses/EDS.html#eds199"

[EDS.courses.201]
title = "Intro/Resources/Tching&Lrning"
catalog = "/courses/EDS.html#eds201"

[EDS.courses.203]
title = "Technology,Teaching & Learning"
catalog = "/courses/EDS.html#eds203"

[EDS.courses.204]
title = "Tech & Professional Assessment"
catalog = "/courses/EDS.html#eds204"

[EDS.courses.206]
title = "Teaching Perf Assessment Portf"
catalog = "/courses/EDS.html#eds206"

[EDS.courses.229]
title = "Intro to Educational Resources"
catalog = "/courses/EDS.html#eds229"

[EDS.courses.232]
title = "Special Topics in Education"
catalog = "/courses/EDS.html#eds232"

[EDS.courses.250]
title = "Equitable Educ/Res & Practice"
catalog = "/courses/EDS.html#eds250"

[EDS.courses.284]
title = "Leadership for Organiztn Devel"
catalog = "/courses/EDS.html#eds284"

[EDS.courses.285]
title = "Leadership for the Future"
catalog = "/courses/EDS.html#eds285"

[EDS.courses.289C]
title = "Disseration Writing Seminar"
catalog = "/courses/EDS.html#eds289c"

[EDS.courses.295]
title = "M. A. Thesis"
catalog = "/courses/EDS.html#eds295"

[EDS.courses.299]
title = "Dissertation Research"
catalog = "/courses/EDS.html#eds299"

[EDS.courses.352B]
title = "Bilingual Instr Practices II"
catalog = "/courses/EDS.html#eds352b"

[EDS.courses.373]
title = "Secondary Engl Teaching Practs"
catalog = "/courses/EDS.html#eds373"

[EDS.courses.374]
title = "Secondary Math Teaching Prac"
catalog = "/courses/EDS.html#eds374"

[EDS.courses.375]
title = "Secondary Sci Teaching Prac"
catalog = "/courses/EDS.html#eds375"

[EDS.courses.376]
title = "Language & Learning Instructn"
catalog = "/courses/EDS.html#eds376"

[EDS.courses.385]
title = "Elem. Schl Math Content & Ped"
catalog = "/courses/EDS.html#eds385"

[ERC]
name = "Eleanor Roosevelt College"

[ERC.courses.103GS]
title = "Paris is Worth a Mass 500-1700"
catalog = "/courses/ERC.html#erc103gs"

[ESYS]
name = "Environmental Systems"

[ESYS.courses.199]
title = "Independent Study"
catalog = "/courses/ESYS.html#esys199"

[ETHN]
name = "Ethnic Studies"

[ETHN.courses.199]
title = "Independent Study and Research"
catalog = "/courses/ETHN.html#ethn199"

[FPM]
name = "Family and Preventive Medicine"

[FPM.courses.286]
title = "Free Clinic II"
catalog = "/courses/FMPH.html#fpm286"

[HDP]
name = "Human Development Program"

[HDP.courses.191]
title = "Field Resrch/Human Development"
catalog = "/courses/HDP.html#hdp191"
note = """Students must visit the HDP Office and submit online questionnaire \
  to pre-enroll in HDP 191. Please visit HDP website for details."""

[HIEU]
name = "History of Europe"

[HIEU.courses.124GS]
title = "The City In Italy"
catalog = "/courses/HIST.html#hieu124gs"

[HINE]
name = "History of the Near East"

[HINE.courses.199]
title = "Independent Study/Near East"
catalog = "/courses/HIST.html#hine199"
note = """Students should go to the History Department Office, HSS 5029, to \
  obtain information and department approval for enrollment in History of the \
  Near East 199."""

[HIUS]
name = "History of the United States"

[HIUS.courses.199]
title = "Independent Study/US History"
catalog = "/courses/HIST.html#hius199"

[HLAW]
name = "Health Law"

[HLAW.courses.205]
title = "Bioethics Sem-Clinical Focus"
catalog = "/courses/HLAW.html#hlaw205"

[HUM]
name = "Humanities"

[HUM.courses.3GS]
title = "Renaissance,Reform&Early Europ"
catalog = "/courses/HUM.html#hum3gs"

[IRGN]
name = "Intrnat Relat/Pac Study-Generl"

[IRGN.courses.499]
title = "Independent Research/Study"
catalog = "/courses/IRPS.html#irgn499"

[JAPN]
name = "Japanese Studies"

[JAPN.courses.10A]
title = "First Year Japanese I"
catalog = "/courses/JAPN.html#japn10a"

[JAPN.courses.10B]
title = "First Year Japanese II"
catalog = "/courses/JAPN.html#japn10b"

[JAPN.courses.10C]
title = "First Year Japanese III"
catalog = "/courses/JAPN.html#japn10c"

[LAWS]
name = "Law and Society"

[LAWS.courses.102S]
title = "Crimes,Civil Wrongs&Constition"
catalog = "/courses/LAWS.html#laws102s"

[LIEO]
name = "Linguistics/Esperanto"

[LIEO.courses.5BS]
title = "Fundamentals of Esperanto II"
catalog = "/courses/LING.html#lieo5bs"

[LIEO.courses.5DS]
title = "Fundamentals of Esperanto IV"
catalog = "/courses/LING.html#lieo5ds"

[LIEO.courses.12S]
title = "Esperanto for Hum & Soc Sci"
catalog = "/courses/LING.html#lieo12s"

[LIFR]
name = "Linguistics/French"

[LIFR.courses.5B]
title = "Fundamentals of French"
catalog = "/courses/LING.html#lifr5b"

[LIFR.courses.5C]
title = "Fundamentals of French"
catalog = "/courses/LING.html#lifr5c"

[LIFR.courses.5D]
title = "Fundamentals of French"
catalog = "/courses/LING.html#lifr5d"

[LIGN]
name = "Linguistics/General"

[LIGN.courses.147GS]
title = "Spanish Dialectology"
catalog = "/courses/LIGN.html#lign147gs"

[LIGN.courses.187GS]
title = "Art Lang & Culture-Flemenco"
catalog = "/courses/LING.html#lign187gs"

[LISP]
name = "Linguistics/Spanish"

[LISP.courses.5A]
title = "Fundamentals of Spanish"
catalog = "/courses/LING.html#lisp5a"

[LISP.courses.5B]
title = "Fundamentals of Spanish"
catalog = "/courses/LING.html#lisp5b"

[LISP.courses.5C]
title = "Fundamentals of Spanish"
catalog = "/courses/LING.html#lisp5c"

[LISP.courses.5D]
title = "Fundamentals of Spanish"
catalog = "/courses/LING.html#lisp5d"

[LTCS]
name = "Literature/Cultural Studies"

[LTCS.courses.199]
title = "Special Studies"
catalog = "/courses/LIT.html#ltcs199"

[LTEN]
name = "Literatures in English"

[LTEN.courses.149GS]
title = "Themes/English&American Lit"
catalog = "/courses/LIT.html#lten149gs"

[LTEN.courses.158GS]
title = "Modern American Literature"
catalog = "/courses/LIT.html#lten158gs"

[LTEN.courses.199]
title = "Special Studies"
catalog = "/courses/LIT.html#lten199"

[LTLA]
name = "Literature/Latin"

[LTLA.courses.4]
title = "Intensive Elementary Latin"
catalog = "/courses/LIT.html#ltla4"

[LTWL]
name = "Literatures of the World"

[LTWL.courses.199]
title = "Special Studies"
catalog = "/courses/LIT.html#ltwl199"

[MAE]
name = "Mechanical & Aerospace Engin"

[MAE.courses.197]
title = "Engineering Internship"
catalog = "/courses/MAE.html#mae197"

[MAE.courses.199]
title = "Independent Study/Undergrads"
catalog = "/courses/MAE.html#mae199"

[MATH]
name = "Mathematics"

[MATH.courses.199]
title = "Independent Study/Undergrad"
catalog = "/courses/MATH.html#math199"
note = """Students should go to the Mathematics Department Office, APM 7018, \
  to obtain information and department approval for enrollment in MATH 199."""

[MATH.courses.199H]
title = "Honors/Thesis Resrch/Undergrad"
catalog = "/courses/MATH.html#math199h"
note = """MATH 199H students should go to the Mathematics Advising Office, \
  APM 6016, to obtain information about the Mathematics Honors Program."""

[MCWP]
name = "Muir College Writing Program"

[MCWP.courses.40]
title = "Critical Writing"
catalog = "/courses/MCWP.html#mcwp40"

[MCWP.courses.50]
title = "Critical Writing"
catalog = "/courses/MCWP.html#mcwp50"
note = """MCWP 50 sections vary in content and emphasis. Course descriptions \
  for MCWP 50 are available in the Muir Writing Program office, HSS 2346, and \
  on our web site: http://muir.ucsd.edu/muir-writing/"""

[MCWP.courses.125]
title = "Argument and Analysis"
catalog = "/courses/MCWP.html#mcwp125"
note = """Students enrolling in MCWP 125: Transfer students with more than \
  ninety units who have fulfilled TAG or IGETC agreements, please come to the \
  Muir College Writing Office HSS 2346 to obtain approval for enrollment on \
  WebReg. MCWP 125 sections vary in content and emphasis. Course descriptions \
  for MCWP 125 are available in the Muir Writing Office, HSS 2346 and on our \
  web site: http://muir.ucsd.edu/muir-writing/"""

[MED]
name = "Medicine"

[MED.courses.199]
title = "Independent Study"

[MMW]
name = "Making of the Modern World"

[MMW.courses.2]
title = "The Great Classical Traditions"
catalog = "/courses/MMW.html#mmw2"

[MMW.courses.3]
title = "The Medieval Heritage"
catalog = "/courses/MMW.html#mmw3"

[MMW.courses.4GS]
title = "New Ideas/Clash of Cultures"
catalog = "/courses/INTD.html#mmw4gs"

[MMW.courses.6GS]
title = "Twentieth Century and Beyond"
catalog = "/courses/INTD.html#mmw6gs"

[MUS]
name = "Music"

[MUS.courses.199]
title = "Independent Study"
catalog = "/courses/MUS.html#mus199"

[PATH]
name = "Pathology"

[PATH.courses.199]
title = "Independent Study"

[PHIL]
name = "Philosophy"

[PHIL.courses.199]
title = "Directed Individual Study"
catalog = "/courses/PHIL.html#phil199"
note = """Students should come to the Philosophy Undergraduate Student \
  Services Office, HSS 7030, to obtain information and department approval for \
  enrollment in Philosophy 199."""

[PHYS]
name = "Physics"

[PHYS.courses.199]
title = "Research for Undergraduates"
catalog = "/courses/PHYS.html#phys199"

[PHYS.courses.298]
title = "Directed Study in Physics"
catalog = "/courses/PHYS.html#phys298"

[POLI]
name = "Political Science"

[POLI.courses.199]
title = "Independent Study"
catalog = "/courses/POLI.html#poli199"

[PSY]
name = "Psychiatry"

[PSY.courses.199]
title = "Independent Study"

[PSYC]
name = "Psychology"

[PSYC.courses.199]
title = "Independent Study"
catalog = "/courses/PSYC.html#psyc199"
note = """Students should go to the Psychology Department Office, \
  Mandler 1533, to obtain information and department approval for enrollment \
  in Psychology 199."""

[SE]
name = "Structural Engineering"

[SE.courses.199]
title = "Independent Study/Undergrads"
catalog = "/courses/SE.html#se199"

[SIO]
name = "Scripps Inst of Oceanography"

[SIO.courses.199]
title = "Special Studies"
catalog = "/courses/SIO.html#sio199"

[SIO.courses.295LS]
title = "Lab Marine Biodivrsty&Consrvtn"
catalog = "/courses/SIO.html#sio295ls"

[SIO.courses.295S]
title = "Marine Biodiversity&Conservatn"
catalog = "/courses/SIO.html#sio295s"

[SOCD]
name = "Soc/Comparative & Historical"

[SOCD.courses.188GS]
title = "Immgratn & Assimiltn-Eurp/Amer"
catalog = "/courses/SOC.html#socd188gs"

[SOMI]
name = "Sch of Med Interdisciplinary"

[SOMI.courses.220]
title = "Core Topics in Biomedical Sci"

[SURG]
name = "Surgery"

[SURG.courses.199]
title = "Independent Study"

[USP]
name = "Urban Studies & Planning"

[USP.courses.199]
title = "Independent Study"
catalog = "/courses/USP.html#usp199"

[VIS]
name = "Visual Arts"

[VIS.courses.122GS]
title = "The City In Italy"
catalog = "/courses/VIS.html#vis122gs"

[VIS.courses.199]
title = "Special Studies"
catalog = "/courses/VIS.html#vis199"
note = """Students should see the Visual Arts Advisor in Mandeville 216 or e-\
  mail vis-ug@ucsd.edu to obtain information/application concerning VIS 199 \
  courses."""

[VIS.courses.295]
title = "Individual Studies/Grad Studnt"
catalog = "/courses/VIS.html#vis295"
